### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/axis#5]
I think we should open source this soon. Things to do before:

- [ ] README should have a list to the deployed version.
- [ ] Add Code of Conduct
- [ ] Add MIT License
- [ ] Add a description to README of the goals of axis
